apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: olafser/ambulance-management-ui
    newName: olafser/ambulance-management-ui
    newTag: 1.0.1  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú