apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ambulance-management-ambulance-ufe-content
spec:
  microFrontend: ambulance-management-ambulance-ufe
  element: ambulance-management-main-container
  attributes:
    - name: base-path
      value: /ambulance-management/
    - name: api-base
      value: /ambulance-management-api
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ambulance-management(/.*)?$"