apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ambulance-management-ambulance-ufe-link
spec:
  microFrontend: polyfea-md-shell
  element: polyfea-md-app
  attributes:
    - name: headline
      value: Ambulance management
    - name: short-headline
      value: Ambulance
    - name: supporting-text
      value: |
        Manage ambulances and their dispatches
    - name: material-icon
      value: emergency
    - name: href
      value: ./ambulance-management
  priority: 10
  displayRules:
    - anyOf:
      - context-name: applications
      - context-name: rail-content
      - context-name: drawer-content