apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: olafser/ambulance-management-ui
    newName: olafser/ambulance-management-ui # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
    newTag: main.20260418.0931 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
  - name: myrres/ambulance-management-webapi
    newName: myrres/ambulance-management-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
    newTag: main # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}