apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: olafser/ambulance-management-ui
    newName: olafser/ambulance-management-ui # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
    newTag: main.20260317.2224 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
